package com.example.whitehacktools.model

object GearDataset {
    val standardGear = listOf(
        Gear(name = "Arrow", weight = "No Size", isContainer = false),
        Gear(name = "Bandage", weight = "No Size", isContainer = false),
        Gear(name = "Blessed/Cursed water", weight = "Minor", isContainer = false),
        Gear(name = "Bolt", weight = "No Size", isContainer = false),
        Gear(name = "Boot", weight = "Minor", isContainer = false),
        Gear(name = "Bottle (wine or beer)", weight = "Minor", isContainer = false),
        Gear(name = "Cart", weight = "Heavy", isContainer = false),
        Gear(name = "Carpeting tool", weight = "Minor", isContainer = false),
        Gear(name = "Case (map or scroll)", weight = "Minor", isContainer = false),
        Gear(name = "Checkers (game)", weight = "No Size", isContainer = false),
        Gear(name = "Climbing gear", weight = "Regular", isContainer = false),
        Gear(name = "Cloth (fine)", weight = "Minor", isContainer = false),
        Gear(name = "Cloth (standard)", weight = "Minor", isContainer = false),
        Gear(name = "Compass", weight = "No Size", isContainer = false),
        Gear(name = "Crowbar", weight = "Minor", isContainer = false),
        Gear(name = "Cult token (fine)", weight = "No Size", isContainer = false),
        Gear(name = "Cult token (simple)", weight = "No Size", isContainer = false),
        Gear(name = "Dice (bone)", weight = "No Size", isContainer = false),
        Gear(name = "Dog", weight = "Heavy", isContainer = false),
        Gear(name = "Flatboat", weight = "Heavy", isContainer = false),
        Gear(name = "Flint & steel", weight = "Minor", isContainer = false),
        Gear(name = "Grapnel", weight = "Regular", isContainer = false),
        Gear(name = "Hammer & Wooden stakes", weight = "Minor", isContainer = false),
        Gear(name = "Hatchet", weight = "Minor", isContainer = false),
        Gear(name = "Holy symbol (silver)", weight = "Minor", isContainer = false),
        Gear(name = "Holy symbol (wooden)", weight = "Minor", isContainer = false),
        Gear(name = "Holy water (small vial)", weight = "Minor", isContainer = false),
        Gear(name = "Horse (battle trained)", weight = "Heavy", isContainer = false),
        Gear(name = "Horse (riding)", weight = "Heavy", isContainer = false),
        Gear(name = "Knapsack", weight = "Minor", isContainer = true),
        Gear(name = "Lab (portable)", weight = "Heavy", isContainer = false),
        Gear(name = "Lamp", weight = "Minor", isContainer = false),
        Gear(name = "Lamp oil", weight = "Minor", isContainer = false),
        Gear(name = "Lockpick", weight = "No Size", isContainer = false),
        Gear(name = "Makeup", weight = "No Size", isContainer = false),
        Gear(name = "Map (regular area)", weight = "No Size", isContainer = false),
        Gear(name = "Match", weight = "No Size", isContainer = false),
        Gear(name = "Mirror (glass)", weight = "Minor", isContainer = false),
        Gear(name = "Mule", weight = "Heavy", isContainer = false),
        Gear(name = "Parchment tube", weight = "Minor", isContainer = false),
        Gear(name = "Perfume", weight = "Minor", isContainer = false),
        Gear(name = "Pole, 10 ft", weight = "Regular", isContainer = false),
        Gear(name = "Prybar", weight = "Minor", isContainer = false),
        Gear(name = "Quiver", weight = "Minor", isContainer = false),
        Gear(name = "Raft", weight = "Heavy", isContainer = false),
        Gear(name = "Ration (day)", weight = "Minor", isContainer = false),
        Gear(name = "Rope, elven", weight = "Minor", isContainer = false),
        Gear(name = "Rope, regular", weight = "Regular", isContainer = false),
        Gear(name = "Sack", weight = "Minor", isContainer = true),
        Gear(name = "Saddle", weight = "Regular", isContainer = false),
        Gear(name = "Saddle bags", weight = "Minor", isContainer = true),
        Gear(name = "Scroll (blank)", weight = "No Size", isContainer = false),
        Gear(name = "Shovel", weight = "Minor", isContainer = false),
        Gear(name = "Shevvak", weight = "Regular", isContainer = false),
        Gear(name = "Skiing gear", weight = "Regular", isContainer = false),
        Gear(name = "Sled", weight = "Heavy", isContainer = false),
        Gear(name = "Sleeping bag", weight = "Regular", isContainer = false),
        Gear(name = "Snare", weight = "Minor", isContainer = false),
        Gear(name = "Snow Monkey", weight = "Heavy", isContainer = false),
        Gear(name = "Spike, iron", weight = "Minor", isContainer = false),
        Gear(name = "Spell book (blank)", weight = "Regular", isContainer = false),
        Gear(name = "Stick (long)", weight = "Regular", isContainer = false),
        Gear(name = "Tent", weight = "Heavy", isContainer = false),
        Gear(name = "Tinderbox", weight = "Minor", isContainer = false),
        Gear(name = "Torch", weight = "Minor", isContainer = false),
        Gear(name = "Warm coat", weight = "Regular", isContainer = false),
        Gear(name = "Water container", weight = "Minor", isContainer = false),
        Gear(name = "Wolvesbane & Garlic", weight = "Minor", isContainer = false),
        Gear(name = "Zoruk (battle)", weight = "Heavy", isContainer = false),
        Gear(name = "Zoruk (riding)", weight = "Heavy", isContainer = false)
    )
}
