package com.example.whitehacktools.model

object WeaponDataset {
    val standardWeapons = listOf(
        Weapon(name = "Axe", damage = "d6", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Axe, Battle", damage = "d8", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Axe, Great", damage = "d10", weight = "Heavy", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Axe, Hand", damage = "d4", weight = "Minor", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Bow", damage = "d6", weight = "Regular", range = "Far", rateOfFire = "1"),
        Weapon(name = "Bow, Long", damage = "d8", weight = "Regular", range = "Far", rateOfFire = "1"),
        Weapon(name = "Bow, Short", damage = "d4", weight = "Minor", range = "Near", rateOfFire = "1"),
        Weapon(name = "Club", damage = "d4", weight = "Minor", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Club, Great", damage = "d8", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Crossbow", damage = "d8", weight = "Regular", range = "Far", rateOfFire = "1/2"),
        Weapon(name = "Crossbow, Hand", damage = "d4", weight = "Minor", range = "Near", rateOfFire = "1"),
        Weapon(name = "Crossbow, Heavy", damage = "d10", weight = "Heavy", range = "Far", rateOfFire = "1/3"),
        Weapon(name = "Dagger", damage = "d4", weight = "Minor", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Flail", damage = "d6", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Flail, Heavy", damage = "d8", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Garrote", damage = "d4", weight = "Minor", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Halberd", damage = "d10", weight = "Heavy", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Hammer", damage = "d4", weight = "Minor", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Hammer, War", damage = "d8", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Javelin", damage = "d6", weight = "Regular", range = "Near", rateOfFire = "1"),
        Weapon(name = "Lance", damage = "d10", weight = "Heavy", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Mace", damage = "d6", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Mace, Heavy", damage = "d8", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Morning Star", damage = "d8", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Net", damage = "0", weight = "Minor", range = "Near", rateOfFire = "1"),
        Weapon(name = "Pick", damage = "d6", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Pike", damage = "d8", weight = "Heavy", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Polearm", damage = "d10", weight = "Heavy", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Sling", damage = "d4", weight = "Minor", range = "Near", rateOfFire = "1"),
        Weapon(name = "Spear", damage = "d6", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Staff", damage = "d4", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Sword, Bastard", damage = "d8/d10", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Sword, Broad", damage = "d8", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Sword, Long", damage = "d8", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Sword, Short", damage = "d6", weight = "Minor", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Sword, Two-Handed", damage = "d10", weight = "Heavy", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Trident", damage = "d6", weight = "Regular", range = "Melee", rateOfFire = "1"),
        Weapon(name = "Whip", damage = "d3", weight = "Minor", range = "Near", rateOfFire = "1")
    )
}
